# 🧠 Agentic AI System - Main Configuration
# Central configuration file for all system components
# Made with ❤️ by Mulky Malikul Dhaher in Indonesia 🇮🇩

# System Information
system:
  name: "Agentic AI System"
  version: "2.0.0"
  description: "Autonomous Multi-Agent Intelligence Platform"
  author: "Mulky Malikul Dhaher"
  country: "Indonesia 🇮🇩"
  license: "MIT"

# Core Configuration
core:
  # Central coordination
  prompt_master:
    enabled: true
    max_concurrent_tasks: 10
    task_timeout: 300
    priority_levels: ["low", "medium", "high", "urgent"]
    
  # Memory management
  memory_bus:
    enabled: true
    max_memory_size: "1GB"
    cleanup_interval: 3600
    persistence_enabled: true
    
  # Agent communication
  sync_engine:
    enabled: true
    websocket_port: 8765
    heartbeat_interval: 30
    message_queue_size: 1000
    
  # Task scheduling
  scheduler:
    enabled: true
    max_scheduled_tasks: 100
    check_interval: 60
    auto_cleanup: true
    
  # AI model selection
  ai_selector:
    enabled: true
    default_provider: "llm7"
    fallback_enabled: true
    response_cache: true

# Agent Configuration
agents:
  # Default settings for all agents
  defaults:
    timeout: 300
    max_retries: 3
    enable_logging: true
    enable_metrics: true
    
  # Individual agent settings
  cybershell:
    enabled: true
    allowed_commands:
      - "ls"
      - "cat"
      - "grep"
      - "find"
      - "git"
      - "npm"
      - "pip"
      - "python"
      - "node"
    blocked_commands:
      - "rm -rf"
      - "format"
      - "del"
      - "sudo rm"
    max_execution_time: 300
    
  agent_maker:
    enabled: true
    max_agents: 50
    default_templates:
      - "data_scientist"
      - "web_developer"
      - "content_writer"
      - "devops_engineer"
    auto_cleanup_unused: true
    
  ui_designer:
    enabled: true
    supported_frameworks:
      - "react"
      - "vue"
      - "angular"
      - "svelte"
    default_styling: "tailwind"
    generate_tests: true
    
  dev_engine:
    enabled: true
    supported_languages:
      - "javascript"
      - "typescript"
      - "python"
      - "java"
      - "go"
    project_templates:
      - "fullstack_web"
      - "mobile_app"
      - "api_service"
      - "microservice"
    auto_install_deps: true
    
  data_sync:
    enabled: true
    supported_databases:
      - "sqlite"
      - "postgresql" 
      - "mysql"
      - "redis"
      - "mongodb"
    backup_interval: 3600
    sync_interval: 300
    
  fullstack_dev:
    enabled: true
    tech_stacks:
      frontend:
        - "react"
        - "vue"
        - "angular"
      backend:
        - "fastapi"
        - "express"
        - "django"
        - "flask"
      database:
        - "postgresql"
        - "mysql"
        - "mongodb"
    
  deploy_manager:
    enabled: true
    platforms:
      - "netlify"
      - "vercel"
      - "railway"
      - "heroku"
      - "aws"
      - "gcp"
      - "docker"
    auto_deploy: false
    health_checks: true
    
  prompt_generator:
    enabled: true
    optimization_enabled: true
    pattern_library: true
    test_prompts: true

# LLM Configuration
llm:
  # Primary provider (LLM7 with free API)
  primary_provider: "llm7"
  
  # Provider configurations
  providers:
    llm7:
      enabled: true
      api_key: "${LLM7_API_KEY}"
      base_url: "https://api.llm7.com/v1"
      models:
        - "gpt-3.5-turbo"
        - "gpt-4"
        - "claude-3-sonnet"
      rate_limit: 60
      free_tier: true
      
    openrouter:
      enabled: true
      api_key: "${OPENROUTER_API_KEY}"
      base_url: "https://openrouter.ai/api/v1"
      models:
        - "openai/gpt-3.5-turbo"
        - "anthropic/claude-3-sonnet"
      rate_limit: 100
      
    camel:
      enabled: true
      api_key: "${CAMEL_API_KEY}"
      base_url: "https://api.camel-ai.org/v1"
      models:
        - "camel-chat"
      rate_limit: 50
      
    openai:
      enabled: false
      api_key: "${OPENAI_API_KEY}"
      base_url: "https://api.openai.com/v1"
      models:
        - "gpt-3.5-turbo"
        - "gpt-4"
      rate_limit: 100
  
  # Failover configuration
  failover:
    enabled: true
    retry_attempts: 3
    retry_delay: 5
    providers_order:
      - "llm7"
      - "openrouter"
      - "camel"
      - "openai"

# Database Configuration
database:
  # Primary database
  primary:
    type: "sqlite"
    url: "sqlite:///data/agentic.db"
    pool_size: 10
    echo: false
    
  # Cache database
  cache:
    type: "redis"
    url: "redis://localhost:6379/0"
    password: "${REDIS_PASSWORD}"
    timeout: 300
    
  # Backup settings
  backup:
    enabled: true
    interval: 3600
    retention_days: 30
    compression: true
    location: "./backups/"

# Web Interface Configuration
web_interface:
  enabled: true
  host: "0.0.0.0"
  port: 5000
  debug: false
  
  # Security settings
  security:
    secret_key: "${SECRET_KEY}"
    session_timeout: 3600
    csrf_protection: true
    rate_limiting: true
    
  # WebSocket settings
  websocket:
    enabled: true
    cors_origins: "*"
    ping_interval: 25
    ping_timeout: 60
    
  # Static files
  static:
    enabled: true
    cache_timeout: 3600
    compression: true

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # File logging
  file:
    enabled: true
    path: "logs/agentic.log"
    max_size: "10MB"
    backup_count: 5
    
  # Console logging
  console:
    enabled: true
    level: "INFO"
    
  # Structured logging
  structured:
    enabled: true
    format: "json"
    include_trace: true

# Monitoring Configuration
monitoring:
  enabled: true
  
  # Metrics collection
  metrics:
    enabled: true
    interval: 60
    retention_days: 7
    
  # Health checks
  health_checks:
    enabled: true
    interval: 30
    endpoints:
      - "/api/system/status"
      - "/api/agents/list"
    
  # Performance monitoring
  performance:
    enabled: true
    track_response_times: true
    track_memory_usage: true
    track_cpu_usage: true
    alert_thresholds:
      response_time: 5000  # ms
      memory_usage: 80     # %
      cpu_usage: 90        # %

# Security Configuration
security:
  # API security
  api:
    rate_limiting:
      enabled: true
      requests_per_minute: 100
      burst_limit: 20
    
    authentication:
      enabled: false  # Disabled for development
      type: "jwt"
      token_expiry: 3600
    
    cors:
      enabled: true
      origins: "*"
      methods: ["GET", "POST", "PUT", "DELETE"]
      headers: ["Content-Type", "Authorization"]
  
  # Input validation
  validation:
    enabled: true
    max_input_size: "10MB"
    sanitize_inputs: true
    
  # Encryption
  encryption:
    enabled: true
    algorithm: "AES-256"
    key_rotation: false

# Development Configuration
development:
  debug: true
  hot_reload: true
  auto_restart: true
  
  # Testing
  testing:
    enabled: true
    test_database: "sqlite:///data/test.db"
    mock_external_apis: true
    
  # Development tools
  tools:
    profiling: false
    debug_toolbar: false
    auto_documentation: true

# Production Configuration
production:
  debug: false
  
  # Performance optimizations
  optimization:
    cache_enabled: true
    compression_enabled: true
    minify_responses: true
    
  # Scaling
  scaling:
    auto_scaling: false
    max_workers: 4
    worker_timeout: 300
    
  # Deployment
  deployment:
    health_check_path: "/health"
    readiness_probe: "/ready"
    graceful_shutdown: true

# Feature Flags
features:
  # Experimental features
  experimental:
    voice_commands: false
    visual_workflow_builder: false
    advanced_analytics: false
    
  # Beta features
  beta:
    mobile_app: false
    desktop_app: false
    browser_extension: false
    
  # Stable features
  stable:
    web_interface: true
    api_endpoints: true
    agent_management: true
    deployment_automation: true

# Regional Configuration (Indonesia)
regional:
  timezone: "Asia/Jakarta"
  locale: "id_ID"
  currency: "IDR"
  
  # Indonesian language support
  language:
    default: "en"
    supported: ["en", "id"]
    auto_detect: true
    
  # Local services integration
  services:
    indonesian_apis: false
    local_payment_gateways: false
    local_cloud_providers: false

# Environment Overrides
# These settings can be overridden by environment variables
environment_overrides:
  DATABASE_URL: "database.primary.url"
  REDIS_URL: "database.cache.url"
  SECRET_KEY: "web_interface.security.secret_key"
  LLM7_API_KEY: "llm.providers.llm7.api_key"
  OPENROUTER_API_KEY: "llm.providers.openrouter.api_key"
  WEB_INTERFACE_PORT: "web_interface.port"
  LOG_LEVEL: "logging.level"
